# Generated by Django 4.1 on 2023-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_address', models.CharField(db_column='local_address', max_length=255, verbose_name='Local Address')),
                ('city', models.CharField(db_column='city', max_length=100, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(db_column='certificate_name', max_length=255, verbose_name='Certificate Name')),
                ('duration', models.PositiveIntegerField(db_column='duration', verbose_name='Duration')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(db_column='profession', max_length=255, verbose_name='Profession')),
            ],
        ),
    ]
