# Generated by Django 4.1 on 2023-10-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='profession',
            index=models.Index(fields=['profession'], name='certificati_profess_7142a9_idx'),
        ),
        migrations.AddIndex(
            model_name='certifications',
            index=models.Index(fields=['certificate_name'], name='certificati_certifi_6eec21_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['local_address'], name='certificati_local_a_46592f_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='certificati_city_ba285e_idx'),
        ),
    ]
