# Generated by Django 4.1 on 2023-10-27 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certification_manager', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='address_local_a_a8c117_idx',
            old_name='certificati_local_a_46592f_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='address_city_db657e_idx',
            old_name='certificati_city_ba285e_idx',
        ),
        migrations.RenameIndex(
            model_name='certifications',
            new_name='certificati_certifi_d4f294_idx',
            old_name='certificati_certifi_6eec21_idx',
        ),
        migrations.RenameIndex(
            model_name='profession',
            new_name='profession_profess_761d70_idx',
            old_name='certificati_profess_7142a9_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='profession', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='certifications',
            table='certifications',
        ),
        migrations.AlterModelTable(
            name='profession',
            table='profession',
        ),
    ]
